// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolymarketPredictor.Persistence;

#nullable disable

namespace PolymarketPredictor.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819112006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolymarketPredictor.Domain.Entities.NormalizedIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentAssetPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<double>("DailyVolatility30d")
                        .HasColumnType("double precision");

                    b.Property<int>("DaysOfPriceHistoryUsed")
                        .HasColumnType("integer");

                    b.Property<int>("DaysToResolution")
                        .HasColumnType("integer");

                    b.Property<double>("DistanceInSigmas")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Liquidity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<double>("PolymarketImpliedProbability")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TrackedMarketId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Volume24h")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("TrackedMarketId", "ComputedAt");

                    b.ToTable("normalized_indicators", (string)null);
                });

            modelBuilder.Entity("PolymarketPredictor.Domain.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NormalizedIndicatorId")
                        .HasColumnType("uuid");

                    b.Property<double>("PredictedProbability")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("RiskNotes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TrackedMarketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedIndicatorId");

                    b.HasIndex("TrackedMarketId", "CreatedAt");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("PolymarketPredictor.Domain.Entities.RawSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TrackedMarketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackedMarketId", "SourceType", "FetchedAt");

                    b.ToTable("raw_snapshots", (string)null);
                });

            modelBuilder.Entity("PolymarketPredictor.Domain.Entities.TrackedMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("ActualOutcome")
                        .HasColumnType("boolean");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CoinGeckoAssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PolymarketConditionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateOnly>("ResolutionDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("ThresholdValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PolymarketConditionId")
                        .IsUnique();

                    b.ToTable("tracked_markets", (string)null);
                });

            modelBuilder.Entity("PolymarketPredictor.Domain.Entities.NormalizedIndicator", b =>
                {
                    b.HasOne("PolymarketPredictor.Domain.Entities.TrackedMarket", "TrackedMarket")
                        .WithMany("NormalizedIndicators")
                        .HasForeignKey("TrackedMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedMarket");
                });

            modelBuilder.Entity("PolymarketPredictor.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("PolymarketPredictor.Domain.Entities.NormalizedIndicator", "NormalizedIndicator")
                        .WithMany("Predictions")
                        .HasForeignKey("NormalizedIndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolymarketPredictor.Domain.Entities.TrackedMarket", "TrackedMarket")
                        .WithMany("Predictions")
                        .HasForeignKey("TrackedMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NormalizedIndicator");

                    b.Navigation("TrackedMarket");
                });

            modelBuilder.Entity("PolymarketPredictor.Domain.Entities.RawSnapshot", b =>
                {
                    b.HasOne("PolymarketPredictor.Domain.Entities.TrackedMarket", "TrackedMarket")
                        .WithMany("RawSnapshots")
                        .HasForeignKey("TrackedMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedMarket");
                });

            modelBuilder.Entity("PolymarketPredictor.Domain.Entities.NormalizedIndicator", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("PolymarketPredictor.Domain.Entities.TrackedMarket", b =>
                {
                    b.Navigation("NormalizedIndicators");

                    b.Navigation("Predictions");

                    b.Navigation("RawSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
